services:
  coraza:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coraza-waf
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./coraza/rules:/etc/coraza/rules:ro
    environment:
      - CORAZA_PROXY_LISTEN=:8080
      - CORAZA_PROXY_UPSTREAM=http://ollama:11434
      - CORAZA_RULES_FILE=/etc/coraza/rules/main.conf

networks:
  proxy:
    name: proxy
    external: false
