version: '3.8'

services:

  coraza:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coraza-waf
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./coraza/rules:/etc/coraza/rules
    environment:
      - CORAZA_PROXY_LISTEN=:9080

networks:
  proxy:
    name: proxy
    external: true

volumes:
  crs_rules:
    name: coraza_crs_rules
